TARGET_VELOCITY: 0.30
VELOCITY_RESOLUTION: 0.06
YAWRATE_RESOLUTION: 0.03
PREDICT_TIME: 10.0
TO_GOAL_COST_GAIN: 1.0
SPEED_COST_GAIN: 1.0
OBSTACLE_COST_GAIN: 2.0
ANGLE_RESOLUTION: 0.0025
MAX_DIST: 10.0
GOAL_THRESHOLD: 0.1
TURN_DIRECTION_THRESHOLD: 0.1
